name: Run Jest Tests        #  Name of the workflow visible in GitHub UI

on: [push]

jobs:                       #  Define a "job" (think: a mini virtual machine)
  test:                     # Job name
    runs-on: ubuntu-latest  #  OS environment

    steps:                  #  Steps inside the job
      - name: Checkout code
        uses: actions/checkout@v3    # Clone repo

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'         # Specify Node version

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test                # This triggers Jest tests!
